services:
  odm:
    image: icr.io/cpopen/odm-k8s/odm:9.5
    hostname: odm
    container_name: odm
    environment:
      - LICENSE=accept
      - SAMPLE=true
    healthcheck:
      test: curl -k -f http://localhost:9060/decisioncenter/healthCheck || exit 1
      interval: 5s
      timeout: 10s
      retries: 30
      start_period: 10s
    ports:
      - 9060:9060
